### ISSUE TITLE
Add minimum version of Thrift in Jaeger exporter build instructions

### ISSUE THREAD

**Issue by varunsh-xilinx** [open-telemetry/opentelemetry-cpp#1108]
**Describe your environment**

Ubuntu 16.04 with Apache Thrift 0.12.0 and trying to build opentelemetry-cpp v1.1.0

**Steps to reproduce**

```
cmake -DWITH_JAEGER=ON -DBUILD_TESTING=OFF -DWITH_EXAMPLES=OFF -DWITH_PROMETHEUS=ON ..
make -j
```

**What is the expected behavior?**
Building should succeed or should make clear why it doesn't work

**What is the actual behavior?**
The build fails with this error:
```
opentelemetry-cpp-1.1.0/exporters/jaeger/src/THttpTransport.h:23:8: error: ‘bool opentelemetry::v1::exporter::jaeger::THttpTransport::isOpen() const’ marked ‘override’, but does not override
   23 |   bool isOpen() const override;
```

**Additional context**
So the reason this fails is that Apache Thrift 0.12.0 doesn't mark `isOpen()` as const so the override fails. Thrift 0.13.0 does mark it const but there may be other build issues with this version. I was able to build with 0.15.0 at least. Could you add some information about what versions of Thrift work in the documentation? Or assert the version in the CMake build?

**Comment by lalitb** [comment]
The versions used in CI env are populated here: https://github.com/open-telemetry/opentelemetry-cpp/blob/main/third_party_release. So it's 0.14.1 for thrift.
But agree, it can be documented more explicitly. Will remove the `bug` label. and add `doc`.
