### ISSUE TITLE
Compile error with GCC 11 WITH_STL=On

### ISSUE THREAD

**Issue by tyler92** [open-telemetry/opentelemetry-cpp#2026]
**Describe your environment** 

gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
cmake version 3.25.1
Ubuntu 20.04

**Steps to reproduce**

```
cmake -DBUILD_TESTING=OFF -DWITH_EXAMPLES_HTTP=ON -DWITH_PROMETHEUS=ON -DWITH_STL=ON ..
make
```

**What is the expected behavior?**

No compile errors

**What is the actual behavior?**

The following error:

```
In file included from opentelemetry-cpp/examples/http/client.cc:7:
opentelemetry-cpp/examples/http/tracer_common.h:29:26: error: expected ‘)’ before ‘&’ token
   29 |   HttpTextMapCarrier<T>(T &headers) : headers_(headers) {}
```

**Additional context**

https://godbolt.org/z/Pv3fqq7zx

**Comment by marcalff** [comment]
Thanks for the report.

According to the compiler explorer link provided (thanks), the code:

* build with GCC 11.3 with C++11, C++14, C++17
* breaks with GCC 11.3 with C++20

which is probably why this did not get detected so far.
