### ISSUE TITLE
Conan recipe not updated for Conan 2.0

### ISSUE THREAD

**Issue by cfrome77** [open-telemetry/opentelemetry-cpp#2130]
Hello, I am working to upgrade the conanfile.py for a project from 1.x to 2.0. When I trying to build, I get this error about the `opentelemetry-proto` recipe not being conan 2.0 comaptible. If you are able to update the recipe to be 2.0 compatible that would be great so that I am able to properly compile using conan 2.0.

```
*********************************************************
Recipe 'opentelemetry-proto/0.19.0' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ImportError: cannot import name 'ConanFile' from 'conans'
```

**Comment by lalitb** [comment]
@seemk by any chance you can help on this?

**Comment by ivgotcrazy** [comment]
![image](https://user-images.githubusercontent.com/3154075/236443637-052f5fc5-cf02-4c98-90e1-b01ffc48c3e2.png)

meet the same problem

**Comment by ivgotcrazy** [comment]
![企业微信截图_16832853734813](https://user-images.githubusercontent.com/3154075/236443853-1fa41049-b1b3-4fbe-a379-903ef9c6a4a5.png)
meet the same problem

**Comment by ivgotcrazy** [comment]
![企业微信截图_16832853734813](https://user-images.githubusercontent.com/3154075/236443992-b8aef810-ca5f-47a1-8441-5ca13263cf06.png)

**Comment by marcalff** [comment]
@cfrome77 

Conan recipe are not maintained in the opentelemetry-cpp or opentelemetry-proto repositories.

From what I understand (not a conan user myself), recipes are maintained here:

* https://github.com/conan-io/conan-center-index

Please see this PR:

* https://github.com/conan-io/conan-center-index/pull/17022

At time of writing, this PR is not merged yet.

**Comment by cfrome77** [comment]
@marcalff 

Thanks for the note on where Conan recipes are maintained. I will coordinate with the MR creator to see when it may get merged, so that I can use it in my code.
