### ISSUE TITLE
Compilation break

### ISSUE THREAD

**Issue by VivekSubr** [open-telemetry/opentelemetry-cpp#1933]
Compiling application with latest opentelemetry release results in error,
```
/usr/include/opentelemetry/nostd/span.h:140:64: error: expected body of lambda expression
                                    std::is_convertible<U (*)[], T (*)[]>::value>::type * = nullptr>
                                                               ^
/usr/include/opentelemetry/nostd/span.h:220:64: error: expected body of lambda expression
            typename std::enable_if<std::is_convertible<U (*)[], T (*)[]>::value>::type * = nullptr>
```

I've tried adding the {} myself, but that still errors out with,
```
/usr/include/opentelemetry/nostd/span.h:140:64: error: expected body of lambda expression
                                    std::is_convertible<U (*)[], T (*)[]>::value>::type * = nullptr>
                                                               ^
/usr/include/opentelemetry/nostd/span.h:220:64: error: expected body of lambda expression
            typename std::enable_if<std::is_convertible<U (*)[], T (*)[]>::value>::type * = nullptr>
```

**Comment by marcalff** [comment]
@VivekSubr 

Thanks for the report.

Please indicate:

- the operating system + version,
- the compiler + version.
- the build framework used (CMake or bazel)
- if `WITH_STL` / `HAVE_CPP_STDLIB` is used or not
- if `WITH_ABSEIL` / `HAVE_ABSEIL` is used of not
- if `WITH_GSL` / `HAVE_GSL` is used or not
- the full CMake options used

Please also paste the full error messages, `opentelemetry/nostd/span.h` is included from somewhere, and we need to understand which compiling unit is causing this include, with the full stack.

**Comment by VivekSubr** [comment]
* OS: Red hat linux, fedora36

* Compiler is clang
[vivek_s@3de5b4016a72 cna]$ clang --version
clang version 13.0.0 (Fedora 13.0.0~rc1-1.fc35)
Target: x86_64-unknown-linux-gnu
Thread model: posix

* Cmake, the command used are,
cmake .. -DBUILD_SHARED_LIBS=ON -DWITH_JAEGER=ON -DWITH_ZIPKIN=ON -DBUILD_TESTING=OFF \
         -DThrift_HOME=$BUILD_DIR/$THRIFT_SRC_DIR
cmake --build . --target all
sudo cmake --install . --config Release --prefix ../.

I'm not enabled any of these flags you mentioned.

Full error is:
In file included from /usr/include/affirmed/logging/genSpan.h:23:
In file included from /usr/include/opentelemetry/sdk/trace/tracer.h:9:
In file included from /usr/include/opentelemetry/sdk/resource/resource.h:6:
In file included from /usr/include/opentelemetry/common/attribute_value.h:8:
/usr/include/opentelemetry/nostd/span.h:140:64: error: expected body of lambda expression
                                    std::is_convertible<U (*)[], T (*)[]>::value>::type * = nullptr>
                                                               ^
/usr/include/opentelemetry/nostd/span.h:220:64: error: expected body of lambda expression
            typename std::enable_if<std::is_convertible<U (*)[], T (*)[]>::value>::type * = nullptr>
                                                               ^
2 errors generated.

**Comment by lalitb** [comment]
With v1.18 in subject line, do you mean otel-cpp v1.8.1 ?
There is no changes in otel-cpp api to cause the error. 
  - Can you check/confirms once again if v.1.8.0 build successfully for you, an v1.8.1 fails.
  - Anything else changed at your end, e.g. Clang version ?

**Comment by VivekSubr** [comment]
@lalitb - tried, same failure... removing 1.8.1 from title.

**Comment by lalitb** [comment]
> tried, same failure... removing 1.8.1 from title.

You mean it works with 1.8.0, and fails with 1.8.1 ? Or it never worked ?

**Comment by VivekSubr** [comment]
Never worked

**Comment by marcalff** [comment]
@VivekSubr 

Thanks for all the details.

Please indicate as well:

- The `CMake` version
- If `CMAKE_CXX_STANDARD` is set, and to which value
- if clang -std=c++11/c++14/etc [option](https://clang.llvm.org/cxx_status.html) is used, and the exact value

I suspect that somehow, the pre C++11 code (`nostd/span.h`) is compiled with a recent C++ standard, and the compiler gets confused by the `[]`, intended to be an array but parsed as a lamdba.

**Comment by VivekSubr** [comment]
@lalitb, looking at /usr/include/opentelemetry/nostd/span.h, it seems it includes std/span.h if we have HAVE_CPP_LIB defined, but it'll still compile the nostd stuff if you don't have std::span, ie C++20 support... which is my case, we are at C++14.

**Comment by ThomsonTan** [comment]
> @lalitb, looking at /usr/include/opentelemetry/nostd/span.h, it seems it includes std/span.h if we have HAVE_CPP_LIB defined, but it'll still compile the nostd stuff if you don't have std::span, ie C++20 support... which is my case, we are at C++14.
> 
> ie, case where HAVE_CPP_LIB is true (since C++14), and HAVE_SPAN is false, that's where compilation is failing. Basically, the nostd::span should be compliable by C++14

I think you meant the flag `HAVE_CPP_STDLIB`? Could install gsl span work in your scenario?

**Comment by lalitb** [comment]
> ie, case where HAVE_CPP_LIB is true (since C++14), and HAVE_SPAN is false, that's where compilation is failing. Basically, the nostd::span should be compliable by C++14

HAVE_CPP_STDLIB would be only true if you are building with WITH_STL option. Can you please reply to @marcalff  comment above with all the options you are using. Thanks.

**Comment by VivekSubr** [comment]
@lalitb @marcalff @ThomsonTan - I added WITH_STL latter, go it to work with WITH_GSL
```
cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS=ON -DWITH_JAEGER=ON -DWITH_ZIPKIN=ON -DBUILD_TESTING=OFF \
      -DThrift_HOME=$BUILD_DIR/$THRIFT_SRC_DIR -DWITH_STL=ON -DWITH_GSL=ON -DGSL_DIR=$BUILD_DIR ..
cmake --build . --target all
sudo cmake --install . --config Release --prefix ../.
```
One minor annoyance here is that you can't set GSL_DIR in command line, I removed the 'set' from CMakeLists.txt to get this working. 

This is resolved for me, thanks again.

**Comment by VivekSubr** [comment]
Patching to remove the enable_if also works (since that's just for performance)

```
diff -urNp opentelemetry-cpp-1.8.1/api/include/opentelemetry/nostd/span.h opentelemetry-cpp-1.8.1-patched/api/include/opentelemetry/nostd/span.h
--- opentelemetry-cpp-1.8.1/api/include/opentelemetry/nostd/span.h      2022-12-04 12:11:21.000000000 -0600
+++ opentelemetry-cpp-1.8.1-patched/api/include/opentelemetry/nostd/span.h      2023-01-27 06:02:20.660992000 -0600
@@ -135,9 +135,7 @@ public:
   }

   template <class U,
-            size_t N,
-            typename std::enable_if<N == Extent &&
-                                    std::is_convertible<U (*)[], T (*)[]>::value>::type * = nullptr>
+            size_t N>
   span(const span<U, N> &other) noexcept : data_{other.data()}
   {}

@@ -216,8 +214,7 @@ public:
   {}

   template <class U,
-            size_t N,
-            typename std::enable_if<std::is_convertible<U (*)[], T (*)[]>::value>::type * = nullptr>
+            size_t N>
   span(const span<U, N> &other) noexcept : extent_{other.size()}, data_{other.data()}
   {}

```

**Comment by owent** [comment]
> @lalitb @marcalff @ThomsonTan - I added WITH_STL latter, go it to work with WITH_GSL
> 
> ```
> cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS=ON -DWITH_JAEGER=ON -DWITH_ZIPKIN=ON -DBUILD_TESTING=OFF \
>       -DThrift_HOME=$BUILD_DIR/$THRIFT_SRC_DIR -DWITH_STL=ON -DWITH_GSL=ON -DGSL_DIR=$BUILD_DIR ..
> cmake --build . --target all
> sudo cmake --install . --config Release --prefix ../.
> ```
> 
> One minor annoyance here is that you can't set GSL_DIR in command line, I removed the 'set' from CMakeLists.txt to get this working.
> 
> This is resolved for me, thanks again.

You can install [Microsoft.GSL](https://github.com/microsoft/gsl) and then use `-DCMAKE_PREFIX_PATH=<where to install Microsoft.GSL>` to tell cmake where to find it.
