### PR TITLE
[BUILD] Fix compiling problems for gcc 4.8

### LINKED ISSUE #3099: Can not compile when using `WITH_STL=CXX11` with legacy toolchain
**Describe your environment** 

Sorry but #3098 only fixes partly problems in #3096 . I will raise another PR to fix the left problems.

OS: Linux
Compiler: GCC 4.8.5
otel-cpp version: 1.17.0

**Steps to reproduce**
Building otel-cpp 1.17.0

**What is the expected behavior?**
Building success.

**What is the actual behavior?**

```bash
// ...
/home/runner/work/cmake-toolset/cmake-toolset/test/third_party/packages/opentelemetry-cpp-v1.17.0/exporters/memory/src/in_memory_metric_exporter_factory.cc:82:26: error: parameter declared ‘auto’
   return Create(data, [](auto) { return AggregationTemporality::kCumulative; });


// ...
/home/runner/work/cmake-toolset/cmake-toolset/test/third_party/packages/opentelemetry-cpp-v1.17.0/exporters/memory/src/in_memory_metric_data.cc: In member function ‘virtual void opentelemetry::v1::exporter::memory::SimpleAggregateInMemoryMetricData::Add(std::unique_ptr<opentelemetry::v1::sdk::metrics::ResourceMetrics>)’:
/home/runner/work/cmake-toolset/cmake-toolset/test/third_party/packages/opentelemetry-cpp-v1.17.0/exporters/memory/src/in_memory_metric_data.cc:34:30: error: converting to ‘std::map<std::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::map<opentelemetry::v1::sdk::common::OrderedAttributeMap, absl::lts_2020_02_25::variant<opentelemetry::v1::sdk::metrics::SumPointData, opentelemetry::v1::sdk::metrics::HistogramPointData, opentelemetry::v1::sdk::metrics::LastValuePointData, opentelemetry::v1::sdk::metrics::DropPointData> > >::key_type {aka std::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >}’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(const _T1&, const _T2&) [with _T1 = std::basic_string<char>; _T2 = std::basic_string<char>]’
         data_[{scope, metric}].insert({pda.attributes, pda.point_data});
                              ^
/home/runner/work/cmake-toolset/cmake-toolset/test/third_party/packages/opentelemetry-cpp-v1.17.0/exporters/memory/src/in_memory_metric_data.cc: In member function ‘const AttributeToPoint& opentelemetry::v1::exporter::memory::SimpleAggregateInMemoryMetricData::Get(const string&, const string&)’:
/home/runner/work/cmake-toolset/cmake-toolset/test/third_party/packages/opentelemetry-cpp-v1.17.0/exporters/memory/src/in_memory_metric_data.cc:44:31: error: converting to ‘std::map<std::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::map<opentelemetry::v1::sdk::common::OrderedAttributeMap, absl::lts_2020_02_25::variant<opentelemetry::v1::sdk::metrics::SumPointData, opentelemetry::v1::sdk::metrics::HistogramPointData, opentelemetry::v1::sdk::metrics::LastValuePointData, opentelemetry::v1::sdk::metrics::DropPointData> > >::key_type {aka std::tuple<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >}’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(const _T1&, const _T2&) [with _T1 = std::basic_string<char>; _T2 = std::basic_string<char>]’
   return data_[{scope, metric}];                    ^
```

### PR DESCRIPTION
**Pull request by owent**
Fixes #3099

## Changes

Fix remaining issues preventing a C++11 build with gcc 4.8.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by marcalff — APPROVED** [review]
LGTM.

File: exporters/memory/src/in_memory_metric_data.cc [hunk 1]
```diff
@@ -31,7 +31,8 @@ void SimpleAggregateInMemoryMetricData::Add(std::unique_ptr<ResourceMetrics> res
       const auto &metric = m.instrument_descriptor.name_;
       for (const auto &pda : m.point_data_attr_)
       {
-        data_[{scope, metric}].insert({pda.attributes, pda.point_data});
```
Comment (ThomsonTan) [inline exporters/memory/src/in_memory_metric_data.cc:34]: Instead of fixing it inline, could we create a separate macro like OPENTELEMETRY_LEGACY, and guard the C++ 11 fix in it? That way, we can find out and cleanup all the C++ 11 workarounds when it can be dropped in future.

Comment (ThomsonTan) [reply exporters/memory/src/in_memory_metric_data.cc:34]: Or if introducing a new macro requires some extra work, perhaps simply add a comment here so say the C++ 11 workaround applied here, so we can locate all of them together later?

Comment (lalitb) [reply exporters/memory/src/in_memory_metric_data.cc:34]: I believe this was agreed in today's meeting to instead add a `TODO:` at places where are adding the C++11 workarounds - please correct me otherwise.

Comment (ThomsonTan) [reply exporters/memory/src/in_memory_metric_data.cc:34]: @lalitb yes. As my second comment mentioned, they easy way would be adding a comment (like TODO) here, so we can find all the C++ 11 workarounds when we can drop the C++ 11 support (assume fully dropping C++ 11 support is still our long term goal).

Comment (owent) [reply exporters/memory/src/in_memory_metric_data.cc:34]: C++ permits a single implicit conversion of a function parameter type. It's more like a bug of GCC 4.8, and I'm not sure if other versions or compilers have similar issues.

File: exporters/memory/src/in_memory_metric_data.cc [hunk 2]
```diff
@@ -31,7 +31,8 @@ void SimpleAggregateInMemoryMetricData::Add(std::unique_ptr<ResourceMetrics> res
...
+        data_[std::tuple<std::string, std::string>{scope, metric}].insert(
+            {pda.attributes, pda.point_data});
```
Comment (marcalff) [inline exporters/memory/src/in_memory_metric_data.cc:35]:
```suggestion
        // NOTE: Explicit type conversion added for C++11 (gcc 4.8)
        data_[std::tuple<std::string, std::string>{scope, metric}].insert(
            {pda.attributes, pda.point_data});
```

File: exporters/memory/src/in_memory_metric_data.cc [hunk 3]
```diff
@@ -41,7 +42,7 @@ const SimpleAggregateInMemoryMetricData::AttributeToPoint &SimpleAggregateInMemo
     const std::string &scope,
     const std::string &metric)
 {
-  return data_[{scope, metric}];
+  return data_[std::tuple<std::string, std::string>{scope, metric}];
```
Comment (marcalff) [inline exporters/memory/src/in_memory_metric_data.cc:45]:
```suggestion
  // NOTE: Explicit type conversion added for C++11 (gcc 4.8)
  return data_[std::tuple<std::string, std::string>{scope, metric}];
```

**Review by marcalff — APPROVED** [review]
