### ISSUE TITLE
unable to build with grpc 1.71.0

### ISSUE THREAD

**Issue by dbarker** [open-telemetry/opentelemetry-cpp#3306]
**Describe your environment** 
main at a57063f7a2

GRPC_VERSION="v1.71.0" 
PROTOBUF_VERSION="29.0" 
ABSEIL_CPP_VERSION="20240722.1"

**Steps to reproduce**

1. Build a docker image with the grpc, protobuf, and abseil versions above
```sh
docker build --build-arg GRPC_VERSION="v1.71.0" --build-arg PROTOBUF_VERSION="29.0" --build-arg ABSEIL_CPP_VERSION="20240722.1" --build-arg USER_UID="$(id -u)" --build-arg USER_GID="$(id -g)"  -t opentelemetry-cpp-dev:latest -f ./.devcontainer/Dockerfile.dev .
```
2. Run a bash session and build the otlp grpc exporter
```sh
docker run -it -v "$PWD:/workspaces/opentelemetry-cpp" opentelemetry-cpp-dev:latest bash

cmake -S . -B ~/build -DWITH_OTLP_GRPC=ON
cmake --build ~/build --parallel
ctest --test-dir ~/build

```

**What is the expected behavior?**
build and test passes

**What is the actual behavior?**
Link error from the `otlp_grpc_exporter_test`
```
/usr/bin/ld: ../../libopentelemetry_proto_grpc.so: undefined reference to `grpc::GetGlobalCallbackHook()'
collect2: error: ld returned 1 exit status
make[2]: *** [exporters/otlp/CMakeFiles/otlp_grpc_exporter_test.dir/build.make:210: exporters/otlp/otlp_grpc_exporter_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:6475: exporters/otlp/CMakeFiles/otlp_grpc_exporter_test.dir/all] Error 2
```

**Additional context**
The `otlp_grpc_exporter_test` adds a link to `gRPC::grpc++` and shouldn't

**Comment by dbarker** [comment]
Closing. Not reproducible. https://github.com/open-telemetry/opentelemetry-cpp/pull/3307#issuecomment-2749528164
